"""
Pydantic Models for RAG API Request/Response Validation

This module defines the data models used by the FastAPI endpoints.
Pydantic automatically validates incoming requests and serializes responses,
ensuring type safety and preventing malformed data from reaching the application.

Benefits of Pydantic:
- Automatic validation (FastAPI returns 422 if validation fails)
- Auto-generated OpenAPI/Swagger docs with schemas
- Type hints improve IDE autocomplete and catch bugs early
- Field descriptions appear in API documentation
"""

from pydantic import BaseModel, Field
from typing import Optional


class RAGUsedContext(BaseModel):
    """
    Product metadata for frontend display (Video 3).

    Represents enriched product information returned to the frontend for visual
    product cards. Contains presentation-layer data fetched from Qdrant.

    Video 3 Addition: Rich Product Context
    ---------------------------------------
    Previous versions only returned text answers. Video 3 enhances the response
    with visual product metadata (images, prices) to enable rich UI cards.

    Fields:
        image_url (Optional[str]): Product image URL from Qdrant
            - May be None if product lacks an image
            - Frontend should handle missing images gracefully (placeholder)
            - Example: "https://m.media-amazon.com/images/I/41vGX4B4DFL._AC_.jpg"

        price (Optional[float]): Product price in USD
            - May be None if pricing data unavailable
            - Frontend can hide price or show "Price unavailable"
            - Example: 39.99

        description (str): Product description from LLM
            - Always present (required field)
            - Generated by instructor from LLM's RAGUsedContext
            - Typically 1-2 sentences with product name
            - Example: "TELSOR Wireless Earbuds for iPhone..."

    Why Optional Fields?
    -------------------
    - Qdrant data quality varies: some products lack images/prices
    - Better UX to show partial data than fail validation
    - Pydantic validation error if None assigned to required float
    - Frontend gracefully degrades when fields are None

    Usage in API Response:
    ---------------------
    Embedded in RAGResponse.used_context as a list:
    {
        "request_id": "...",
        "answer": "...",
        "used_context": [
            {"image_url": "...", "price": 39.99, "description": "..."},
            {"image_url": null, "price": null, "description": "..."}  # Graceful degradation
        ]
    }
    """
    image_url: Optional[str] = Field(None, description="The URL of the image of the item")
    price: Optional[float] = Field(None, description="The price of the item")
    description: str = Field(..., description="The description of the item")


class RAGRequest(BaseModel):
    """
    Request model for RAG Q&A endpoint.

    Validates incoming POST requests to /rag/.
    FastAPI automatically parses JSON body and validates against this schema.

    Attributes:
        query (str): User's question about products
                    Required field (no default value)
                    Example: "What are the best wireless headphones?"

    Validation rules:
        - query must be present (... = required, no default)
        - query must be a string
        - Empty strings are allowed (could add min_length=1 to prevent)

    Example valid request:
        {
            "query": "What are the best wireless headphones?"
        }

    Example invalid request (400 Bad Request):
        {
            "question": "..."  # Wrong field name
        }
        {} # Missing required field

    Why Field():
        - Adds description to OpenAPI docs
        - Allows additional validation (min_length, max_length, regex, etc.)
        - ... means required (equivalent to Field(default=...))

    Future enhancements:
        - Add query length validation: Field(..., min_length=1, max_length=500)
        - Add examples for better API docs: Field(..., examples=["best laptops"])
        - Add query sanitization to prevent prompt injection
    """

    query: str = Field(..., description="The query to be used in the RAG pipeline")


class RAGResponse(BaseModel):
    """
    Response model for RAG Q&A endpoint (Video 3: Enhanced with product context).

    Defines the structure of successful responses from /rag/.
    FastAPI automatically serializes Python objects to JSON based on this schema.

    Attributes:
        request_id (str): Unique identifier for request tracing
                         Generated by RequestIDMiddleware as UUID v4
                         Example: "bf802801-da21-4b61-a10c-e700d4aafe2e"

        answer (str): Natural language answer generated by the LLM
                     Contains product recommendations based on retrieved context
                     Example: "Based on the available products, I recommend..."

        used_context (list[RAGUsedContext]): Product metadata for frontend display (Video 3)
                     List of enriched product information with images, prices, descriptions
                     Only includes products actually referenced in the answer
                     Frontend uses this to render visual product cards

    Video 3 Enhancement: Rich Product Context
    -----------------------------------------
    Previous versions only returned text answers. Video 3 adds used_context
    to enable rich frontend displays with product images and pricing.

    Example response (Video 3):
        {
            "request_id": "bf802801-da21-4b61-a10c-e700d4aafe2e",
            "answer": "The best wireless headphones are the TELSOR Earbuds...",
            "used_context": [
                {
                    "image_url": "https://m.media-amazon.com/images/I/41vGX4B4DFL._AC_.jpg",
                    "price": 39.99,
                    "description": "TELSOR Wireless Earbuds for iPhone..."
                },
                {
                    "image_url": "https://m.media-amazon.com/images/I/4117ZOD57DL._AC_.jpg",
                    "price": 29.99,
                    "description": "Open Ear Headphones Bluetooth 5.3..."
                }
            ]
        }

    Why include request_id in response:
        - Allows client to reference specific request in support tickets
        - Enables correlation between client logs and server logs
        - Useful for debugging: client can say "request XYZ returned wrong answer"
        - Appears in both response body and X-Request-ID header

    Why include used_context (Video 3):
        - Enables visual product cards in frontend
        - Provides actionable data: users can see/buy products mentioned
        - Improves trust: users see actual products backing the answer
        - Better UX: images + prices more engaging than text alone

    Future enhancements:
        - Add confidence_score field: measure of answer quality
        - Add processing_time field: how long RAG pipeline took
        - Add similarity_scores: relevance of each product
        - Add stock_status: product availability
    """

    request_id: str = Field(..., description="The request ID")
    answer: str = Field(..., description="The answer to the query")
    used_context: list[RAGUsedContext] = Field(
        ..., description="Information about the items used to answer the query"
    )
