"""
Pydantic Models for RAG API Request/Response Validation

This module defines the data models used by the FastAPI endpoints.
Pydantic automatically validates incoming requests and serializes responses,
ensuring type safety and preventing malformed data from reaching the application.

Benefits of Pydantic:
- Automatic validation (FastAPI returns 422 if validation fails)
- Auto-generated OpenAPI/Swagger docs with schemas
- Type hints improve IDE autocomplete and catch bugs early
- Field descriptions appear in API documentation
"""

from pydantic import BaseModel, Field


class RAGRequest(BaseModel):
    """
    Request model for RAG Q&A endpoint.

    Validates incoming POST requests to /rag/.
    FastAPI automatically parses JSON body and validates against this schema.

    Attributes:
        query (str): User's question about products
                    Required field (no default value)
                    Example: "What are the best wireless headphones?"

    Validation rules:
        - query must be present (... = required, no default)
        - query must be a string
        - Empty strings are allowed (could add min_length=1 to prevent)

    Example valid request:
        {
            "query": "What are the best wireless headphones?"
        }

    Example invalid request (400 Bad Request):
        {
            "question": "..."  # Wrong field name
        }
        {} # Missing required field

    Why Field():
        - Adds description to OpenAPI docs
        - Allows additional validation (min_length, max_length, regex, etc.)
        - ... means required (equivalent to Field(default=...))

    Future enhancements:
        - Add query length validation: Field(..., min_length=1, max_length=500)
        - Add examples for better API docs: Field(..., examples=["best laptops"])
        - Add query sanitization to prevent prompt injection
    """

    query: str = Field(..., description="The query to be used in the RAG pipeline")


class RAGResponse(BaseModel):
    """
    Response model for RAG Q&A endpoint.

    Defines the structure of successful responses from /rag/.
    FastAPI automatically serializes Python objects to JSON based on this schema.

    Attributes:
        request_id (str): Unique identifier for request tracing
                         Generated by RequestIDMiddleware as UUID v4
                         Example: "bf802801-da21-4b61-a10c-e700d4aafe2e"

        answer (str): Natural language answer generated by the LLM
                     Contains product recommendations based on retrieved context
                     Example: "Based on the available products, I recommend..."

    Example response:
        {
            "request_id": "bf802801-da21-4b61-a10c-e700d4aafe2e",
            "answer": "Based on the available products, I recommend..."
        }

    Why include request_id in response:
        - Allows client to reference specific request in support tickets
        - Enables correlation between client logs and server logs
        - Useful for debugging: client can say "request XYZ returned wrong answer"
        - Appears in both response body and X-Request-ID header

    Future enhancements:
        - Add retrieved_products field: list of product IDs used in answer
        - Add confidence_score field: measure of answer quality
        - Add processing_time field: how long RAG pipeline took
        - Add sources field: which products contributed to answer
    """

    request_id: str = Field(..., description="The request ID")
    answer: str = Field(..., description="The answer to the query")
